language: scala
scala:
- 2.11.7
sbt_args: -no-colors -J-Xss2m
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
after_success:
- sbt one-jar
deploy:
  provider: releases
  api_key:
    secure: bGItcNV9GFDy/+ZVdcBqFkd5gZa52f3ueXw9x7Il5x0yzx7s+L+4fnfl853V9LF5MXtCFcLB76MJYoN7nBXOwu5BS6ka8Fkp3VsmyCl4q5oBCliu+Z40TDSrOnadz+MdgNyMFlPiIETVdZxaSBgd30uDWjSbo/XzI4YPALkxwjkRE8dQ4z5HZn8XfMVbHMjisqvEwAf2WmPBf74KVs2m/lFGBZbBZa+no+IFAgMQUFaxwTCFK1xvJ6z9M/9Oa7/bvNapIHCcpDvZmYxbP3089N4n6J5l5WFoZv9W5nEP+1iCHs/4MN6WEHzmh5cr5TG1dsYqvG7gpfEPkyOxwg/0Ki5Kp2Z0wg8+tOXAvYvW73375iqMbbvC69gOIzCJEs5E0K9sHehGHNRHR8lHBhY5Vb3LRf0eigFliU9e36wP8sIrNue+U3qXt97DeGsjsC+9q61QVSnN/ymNaIt2xoqn+LhDP8dqQbA/oeu5sWYLac8g9cgBN3rocBt47bWmI+TSsupPeBZ5HfevMygStvt9bEVP3Ky4aVg7Uo/aSnsvOaOm7FwvM/sch2CjkiiMdeHBHIjY7HwoBjsGY9Irp3Q20rka6z3jZrkn17D9jQmJ5IiEh499VeKWa4RBMDoxV+mxkkDY9KrVGOzSGD2ufYnSBnd/AkzX0seTFPGHwpQFv94=
  file: /target/scala-2.11/cloud-client_2.11-1.0-one-jar.jar
  on:
    tags: true
env:
  global:
    secure: OAyLVl/Nfoguv+6IQZQTXikXMPGJTB0Qt1FFhgUf1VyylVLc9NOtk506L1Z/prgCd4p5LZJeq/3nkSOkXm6D29TqvW8pd0Wclk7M6xEFL9FVvrrdrySAgbeFEFPepQzneYtuoAXuE/AGksXGgJ2U2SizWpeeXiiAdFHQO4kM2X/4SYnwG62Iim0GuTpo9mkhOAoEumBYn+DRjpVcM77S85G1MLEo0CBRYCr8n6woPrjon+A42BQv74J2Y8EX7j3aIDXoWcSbjxX963iKHROX2vGTHd0BTnVg2KKdIAn4ojVMrJJWzdp24GVlv1HEFWw2aTR6pE8PPZXSUxbjuZzLoJ6bUbz2aLL/0adoyIrUYltg8c7hPjfJnzVq/tDL/OL9z+4zjDlGzn112Wxun/TnhKFgohm7YFExVrJs77ur8UIYLmR/2IIIB01g9cyEZVl1a8QxrM1pRmiRVxLR2u0VPfuelwEeqt2QHSk6fItpCnmFl+DFipboAUP0aygs9K57viqzd3BbGQ4CGIVkIrfaQC1xiLip4PTYqWEkRkSwU5HKPX9YVDQczKmR8vHxYLmv0SPQesgg4c0ikJSHI8lM3Amr9hIGBHBCADv9lRBQEo3BEHt1JyQlcg4XeLgxGBvgeRHk4OViUQ6hU/2KNEdR7yMW7Ln9UVR1H0w18HIILu4=
