language: scala
scala:
- 2.11.7
sbt_args: -no-colors -J-Xss2m
jdk:
- oraclejdk8
- oraclejdk7
- openjdk6
after_success:
- sbt one-jar
secure: "NO+HqVRAhuzRzSdDU/zpijnRs/DumD/9bA1uIlcvOKF7Mmp3RN1IEUIaaZm3PeXB7VcJPkBKGq0PvY+HJMuh/bsIjIy7lT1RquaFtO6NOf3LGC3CD7125cHQYVuKBJP2AFhEluaE8xxzwhFO0p20QjxrrnFOP5XTnKw9E9zDVV+83RFtdtrO8xkAZCpewB0Dg5ubiyfN7OhyLT/+c57isy5SK3Jo6ia+HzbB9B6McHIZbO9QMwHp8+tDLSxV4g3/xMd7RRCKe2jd6PEpH63r8IYpeiA8tLWPj2pc0oNopPE2e3GKV6BnTsqO32T7XGLGdRE8N9vCN57MP51wGu3xATwaRT2XlM8Gkz3+KabY8AGFuACcR2TcKb4tGxOU7kTw69aH44GcnPma814oT0ruYQBoxbFY78VPj214j/9I7AhSUdNDGhF1xyCIn2ChtxGCjQYPbJ8Z0lCJkLeHoSAgrHNN7bm2c6rtAOuz7Y6MhHi/zpHt0krwfVq1pZ+soWryiA1DM5rsaTBgiwkFTuYxWSSLUwJ8Q6iWX8lLVD7E4GA1x1eejvTyU1BHv3+avn2I7EAvUC6dHKBWYX1mYjQgp86MPFPluXv4H3KNTyelM6koWCkdm4G+i7QjnDlYStInAxBzMVfsUOUsNkhliGsTWwIynrCgeRkukVtCUgWBocQ="
deploy:
  provider: releases
  api_key:
    secure: bGItcNV9GFDy/+ZVdcBqFkd5gZa52f3ueXw9x7Il5x0yzx7s+L+4fnfl853V9LF5MXtCFcLB76MJYoN7nBXOwu5BS6ka8Fkp3VsmyCl4q5oBCliu+Z40TDSrOnadz+MdgNyMFlPiIETVdZxaSBgd30uDWjSbo/XzI4YPALkxwjkRE8dQ4z5HZn8XfMVbHMjisqvEwAf2WmPBf74KVs2m/lFGBZbBZa+no+IFAgMQUFaxwTCFK1xvJ6z9M/9Oa7/bvNapIHCcpDvZmYxbP3089N4n6J5l5WFoZv9W5nEP+1iCHs/4MN6WEHzmh5cr5TG1dsYqvG7gpfEPkyOxwg/0Ki5Kp2Z0wg8+tOXAvYvW73375iqMbbvC69gOIzCJEs5E0K9sHehGHNRHR8lHBhY5Vb3LRf0eigFliU9e36wP8sIrNue+U3qXt97DeGsjsC+9q61QVSnN/ymNaIt2xoqn+LhDP8dqQbA/oeu5sWYLac8g9cgBN3rocBt47bWmI+TSsupPeBZ5HfevMygStvt9bEVP3Ky4aVg7Uo/aSnsvOaOm7FwvM/sch2CjkiiMdeHBHIjY7HwoBjsGY9Irp3Q20rka6z3jZrkn17D9jQmJ5IiEh499VeKWa4RBMDoxV+mxkkDY9KrVGOzSGD2ufYnSBnd/AkzX0seTFPGHwpQFv94=
  file: /target/scala-2.11/cloud-client_2.11-1.0-one-jar.jar
  on:
    tags: true
